
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module EE314_vga(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS
);

wire [7:0] game_to_vga; 

top game(
    .clk_50MHz(MAX10_CLK1_50),
    .reset(0),  
	 .menu_select(SW[9:8]), 
	 .attack_direction_1(SW[4]),
	 .player1_attack(SW[1:0]),	 
	 .player1_left(SW[2]),
	 .player1_right(SW[3]),
	 .game_over_sig(SW[7]),
    .hsync(VGA_HS),          
    .vsync(VGA_VS),          
    .rgb(game_to_vga)       
    );

assign VGA_R = {1'b0, game_to_vga[7:5]}; // 3 bits -> 4 bits
assign VGA_G = {1'b0, game_to_vga[4:2]}; // 3 bits -> 4 bits
assign VGA_B = {2'b00, game_to_vga[1:0]}; // 2 bits -> 4 bits

endmodule